// adapters/ed25519.ts — ELEMENTARY grade (the nursery DEFAULT for real projects)
//
// Asymmetric, durable, dependency-free. One Ed25519 keypair per issuer, generated by
// node:crypto and persisted under .data/ed25519/<issuer>/: the private key as key.pem
// (PKCS8, mode 0600, written once with 'wx' so exactly one process creates it) and the
// public half as key.pub (SPKI — the file you hand to verifiers; they never need anything
// else). The private key is loaded into a KeyObject and used in place; nothing on the port
// ever carries it. That earns `asymmetric-keys` + `key-persisted`, which together with the
// port-guaranteed expiry enforcement satisfies everything the nursery->elementary gate
// activates.

import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { createHash, createPrivateKey, createPublicKey, generateKeyPairSync, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto'
import type { KeyObject } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Adapter, Attestor, Claim, KeyInfo, Proof, VerifyResult } from '../port.ts'
import { assertValidClaim, canonicalClaim, claimExpired, proofShapeError } from '../port.ts'

const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '.data', 'ed25519')
const ALGORITHM = 'ed25519'

interface Key {
  keyId: string // sha256 fingerprint of the public key (SPKI DER), truncated
  createdAt: string
  privateKey: KeyObject
  publicKey: KeyObject
}

export function keyIdOf(publicKey: KeyObject): string {
  return createHash('sha256')
    .update(publicKey.export({ type: 'spki', format: 'der' }))
    .digest('hex')
    .slice(0, 16)
}

// Load-or-create: key.pem is the source of truth ('wx' + 0600); the public key and keyId
// derive from it, so there is no second file to fall out of sync. createdAt is the pem's
// mtime — it is written once and never rewritten.
async function loadKey(issuer: string): Promise<Key> {
  const dir = join(DATA_DIR, issuer.replace(/[^a-z0-9_-]/gi, '_'))
  await mkdir(dir, { recursive: true })
  const pemPath = join(dir, 'key.pem')
  let pem: string
  try {
    pem = await readFile(pemPath, 'utf8')
  } catch {
    try {
      await writeFile(pemPath, generateKeyPairSync('ed25519').privateKey.export({ type: 'pkcs8', format: 'pem' }), { flag: 'wx', mode: 0o600 })
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== 'EEXIST') throw e // lost the race — use the winner's key
    }
    pem = await readFile(pemPath, 'utf8')
  }
  const privateKey = createPrivateKey(pem)
  const publicKey = createPublicKey(privateKey)
  try {
    await writeFile(join(dir, 'key.pub'), publicKey.export({ type: 'spki', format: 'pem' }), { flag: 'wx' })
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'EEXIST') throw e
  }
  return { keyId: keyIdOf(publicKey), createdAt: (await stat(pemPath)).mtime.toISOString(), privateKey, publicKey }
}

class Ed25519Attestor implements Attestor {
  private key: Key

  constructor(key: Key) {
    this.key = key
  }

  async sign(claim: Claim): Promise<Proof> {
    assertValidClaim(claim)
    const signature = cryptoSign(null, Buffer.from(canonicalClaim(claim)), this.key.privateKey).toString('hex')
    return { claim, keyId: this.key.keyId, algorithm: ALGORITHM, signature }
  }

  // Fail-closed: every exit is {valid:false, reason} or {valid:true, claim}. Never a throw.
  async verify(proof: Proof): Promise<VerifyResult> {
    try {
      const shape = proofShapeError(proof)
      if (shape) return { valid: false, reason: shape }
      if (proof.algorithm !== ALGORITHM) return { valid: false, reason: `unknown-algorithm: ${proof.algorithm}` }
      if (proof.keyId !== this.key.keyId) return { valid: false, reason: 'unknown-key' }
      let ok = false
      try {
        ok = cryptoVerify(null, Buffer.from(canonicalClaim(proof.claim)), this.key.publicKey, Buffer.from(proof.signature, 'hex'))
      } catch {
        ok = false // a signature so garbled the primitive rejects its shape is just a bad signature
      }
      if (!ok) return { valid: false, reason: 'bad-signature' }
      if (claimExpired(proof.claim)) return { valid: false, reason: 'expired' }
      return { valid: true, claim: proof.claim }
    } catch (e) {
      return { valid: false, reason: `verify-error: ${(e as Error).message}` }
    }
  }

  async keyInfo(): Promise<KeyInfo> {
    return { keyId: this.key.keyId, createdAt: this.key.createdAt, algorithm: ALGORITHM }
  }
  async close(): Promise<void> {}
}

export const adapter: Adapter = {
  name: 'ed25519',
  maxGrade: 'elementary',
  capabilities: ['expiry-enforced', 'asymmetric-keys', 'key-persisted'],
  async open(issuer: string): Promise<Attestor> {
    return new Ed25519Attestor(await loadKey(issuer))
  },
}
